version: 2
registries:
  nuget: # Define access for a private registry
    type: nuget-feed
    url: https://nuget.pkg.github.com/trifork/index.json
    username: cheetahbot
    password: ${{secrets.CHEETAH_READ_TOKEN}}
updates:
  - package-ecosystem: "nuget"
    directory: "/src/Cheetah.WebApi/"
    registries:
      - nuget # Allow version updates for dependencies in this registry
    schedule:
      interval: "daily"
      time: "10:00"
      timezone: Europe/Copenhagen
