site_name: "Cheetah.WebApi"

nav:
  - Home: index.md

plugins:
  - techdocs-core
  - kroki:
      ServerURL: https://kroki.cheetah.trifork.dev
      EnableMermaid: false
      EnableBlockDiag: false
      Enablebpmn: false
      EnableExcalidraw: false
